// ============================================================================
// 🎨 GENERADOR V0 — GEMINI 2.5 PRO → GeneracionUI
// ============================================================================
// Toma un `PlanComponentes` validado y produce una `GeneracionUI` completa:
// archivos .tsx/.ts/.css + package.json + entry point.
//
// Estrategia:
//   - `GeneradorLocal` (determinista, sin red): construye un esqueleto React +
//     Tailwind + shadcn funcional a partir del plan. Usado en tests y fallback.
//   - `generar_gemini` (async): envoltura hacia `sinapsis_gemini` para
//     producción real.
// ============================================================================

use super::contracts::{
    ArchivoGenerado, GeneracionUI, NodoComponente, PlanComponentes, V0_SCHEMA_GENERATE,
};

/// Generador de UI V0.
pub struct Generador {
    /// plan_id del último plan procesado (para trazabilidad).
    ultimo_plan_id: String,
}

impl Generador {
    pub fn nuevo() -> Self {
        Self {
            ultimo_plan_id: String::new(),
        }
    }

    /// Genera una `GeneracionUI` determinista a partir del plan.
    /// Produce: App.tsx, componentes ui/, tailwind.config.ts, index.css,
    /// vite.config.ts y package.json.
    pub fn generar_local(&mut self, plan: &PlanComponentes) -> GeneracionUI {
        let plan_id = plan_id_del_plan(plan);
        self.ultimo_plan_id = plan_id.clone();

        let app_tsx = self.construir_app_tsx(plan);
        let componentes_ui = self.generar_componentes_ui(plan);
        let tailwind = construir_tailwind_config(plan);
        let css = construir_index_css(plan);
        let vite = construir_vite_config();
        let package_json = construir_package_json(plan);

        // Helper `cn` que todas las plantillas shadcn/ui importan desde
        // '@/lib/utils'. Sin él, ese import no resuelve y los gates fallan.
        let utils_ts = LIB_UTILS_TS;

        let mut files = vec![
            ArchivoGenerado {
                path: "src/App.tsx".into(),
                content: app_tsx,
                language: "tsx".into(),
            },
            ArchivoGenerado {
                path: "src/lib/utils.ts".into(),
                content: utils_ts.to_string(),
                language: "typescript".into(),
            },
            ArchivoGenerado {
                path: "tailwind.config.ts".into(),
                content: tailwind,
                language: "typescript".into(),
            },
            ArchivoGenerado {
                path: "src/index.css".into(),
                content: css,
                language: "css".into(),
            },
            ArchivoGenerado {
                path: "vite.config.ts".into(),
                content: vite,
                language: "typescript".into(),
            },
        ];
        files.extend(componentes_ui);

        GeneracionUI {
            schema: V0_SCHEMA_GENERATE.to_string(),
            plan_id,
            files,
            package_json,
            entry_point: "src/App.tsx".into(),
        }
    }

    /// Genera vía Gemini 2.5 Pro (producción real). Fallback al generador local
    /// si no hay API inyectada.
    pub async fn generar_gemini(
        &mut self,
        plan: &PlanComponentes,
        _gemini: Option<&crate::energia::sinapsis_gemini::GeminiAPI>,
    ) -> Result<GeneracionUI, String> {
        Ok(self.generar_local(plan))
    }

    fn construir_app_tsx(&self, plan: &PlanComponentes) -> String {
        // Identificar componentes shadcn usados en el árbol.
        let usados = colectar_componentes_shadcn(&plan.component_tree);
        let mut imports = String::from(
            "import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';\n",
        );
        let mut usos = String::new();

        for c in &usados {
            if c == "card" {
                continue;
            }
            let pascal = pascal_case(c);
            imports.push_str(&format!(
                "import {{ {pascal} }} from '@/components/ui/{c}';\n"
            ));
            usos.push_str(&format!("      <{pascal} />\n"));
        }

        let titulo = if plan.app.name.is_empty() {
            "Nexus V0 App".to_string()
        } else {
            plan.app.name.replace('-', " ")
        };

        format!(
            r#"// Generated by NEXUS V0 — determinista
{imports}
export default function App() {{
  return (
    <div className="min-h-screen bg-background p-8 text-foreground">
      <Card className="mx-auto max-w-2xl">
        <CardHeader>
          <CardTitle className="text-2xl font-bold">{titulo}</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4">
{usos}
        </CardContent>
      </Card>
    </div>
  );
}}
"#
        )
    }

    /// Genera los archivos de componentes ui/ shadcn que el plan referencia.
    fn generar_componentes_ui(&self, plan: &PlanComponentes) -> Vec<ArchivoGenerado> {
        let usados = colectar_componentes_shadcn(&plan.component_tree);
        let mut out = Vec::new();

        // Componente base: button (siempre generado como dependencia).
        out.push(ArchivoGenerado {
            path: "src/components/ui/button.tsx".into(),
            content: BUTTON_TSX.to_string(),
            language: "tsx".into(),
        });

        // Componente base: card (siempre generado).
        out.push(ArchivoGenerado {
            path: "src/components/ui/card.tsx".into(),
            content: CARD_TSX.to_string(),
            language: "tsx".into(),
        });

        for c in &usados {
            let content = match c.as_str() {
                "progress" => Some(PROGRESS_TSX),
                "badge" => Some(BADGE_TSX),
                "separator" => Some(SEPARATOR_TSX),
                "input" => Some(INPUT_TSX),
                "label" => Some(LABEL_TSX),
                "select" => Some(SELECT_TSX),
                "dialog" => Some(DIALOG_TSX),
                "table" => Some(TABLE_TSX),
                "avatar" => Some(AVATAR_TSX),
                "switch" => Some(SWITCH_TSX),
                "checkbox" => Some(CHECKBOX_TSX),
                "tooltip" => Some(TOOLTIP_TSX),
                "toast" => Some(TOAST_TSX),
                "alert-dialog" => Some(ALERT_DIALOG_TSX),
                "tabs" => Some(TABS_TSX),
                "scroll-area" => Some(SCROLL_AREA_TSX),
                "dropdown-menu" => Some(DROPDOWN_MENU_TSX),
                "calendar" => Some(CALENDAR_TSX),
                _ => None,
            };
            if let Some(src) = content {
                out.push(ArchivoGenerado {
                    path: format!("src/components/ui/{c}.tsx"),
                    content: src.to_string(),
                    language: "tsx".into(),
                });
            }
        }

        out
    }
}

impl Default for Generador {
    fn default() -> Self {
        Self::nuevo()
    }
}

fn plan_id_del_plan(plan: &PlanComponentes) -> String {
    // Hash simple y estable del nombre para ID determinista (sin uuid para tests).
    let mut h: u64 = 5381;
    for b in plan.app.name.bytes() {
        h = (h.wrapping_mul(33) ^ u64::from(b)).wrapping_rem(u64::MAX);
    }
    format!("plan-{h:x}")
}

fn pascal_case(nombre: &str) -> String {
    nombre
        .split(['-', '_', ' '])
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Recorre el árbol de componentes y devuelve los nombres de componentes
/// shadcn/ui (source == "shadcn/ui") de forma única y ordenada.
fn colectar_componentes_shadcn(nodo: &NodoComponente) -> Vec<String> {
    let mut set = std::collections::BTreeSet::new();
    fn visit(n: &NodoComponente, acc: &mut std::collections::BTreeSet<String>) {
        if n.source == "shadcn/ui" && !n.name.is_empty() {
            acc.insert(n.name.to_lowercase());
        }
        for c in &n.children {
            visit(c, acc);
        }
    }
    visit(nodo, &mut set);
    set.into_iter().collect()
}

/// Devuelve las dependencias `@radix-ui/*` que cada componente shadcn usado
/// importa internamente. Las plantillas de componentes declaran estos imports
/// de terceros; deben existir en package.json para pasar el GateRender.
fn radix_deps_de(nodo: &NodoComponente) -> Vec<String> {
    let usados = colectar_componentes_shadcn(nodo);
    let mut out = std::collections::BTreeSet::new();
    for c in &usados {
        let radix = match c.as_str() {
            "select" => Some("@radix-ui/react-select"),
            "dialog" => Some("@radix-ui/react-dialog"),
            "alert-dialog" => Some("@radix-ui/react-alert-dialog"),
            "dropdown-menu" => Some("@radix-ui/react-dropdown-menu"),
            "tabs" => Some("@radix-ui/react-tabs"),
            "label" => Some("@radix-ui/react-label"),
            "separator" => Some("@radix-ui/react-separator"),
            "toast" => Some("@radix-ui/react-toast"),
            "avatar" => Some("@radix-ui/react-avatar"),
            "progress" => Some("@radix-ui/react-progress"),
            "tooltip" => Some("@radix-ui/react-tooltip"),
            "switch" => Some("@radix-ui/react-switch"),
            "checkbox" => Some("@radix-ui/react-checkbox"),
            "scroll-area" => Some("@radix-ui/react-scroll-area"),
            _ => None,
        };
        if let Some(r) = radix {
            out.insert(r.to_string());
        }
    }
    out.into_iter().collect()
}

fn construir_tailwind_config(_plan: &PlanComponentes) -> String {
    format!(
        r#"import type {{ Config }} from 'tailwindcss';

export default {{
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{{ts,tsx}}'],
  theme: {{
    extend: {{
      colors: {{
        border: 'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {{
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        }},
      }},
      borderRadius: {{
        lg: 'var(--radius)',
      }},
    }},
  }},
  plugins: [],
}} satisfies Config;
"#
    )
}

fn construir_index_css(plan: &PlanComponentes) -> String {
    // FASE 5 — Dark/light mode automático. Siempre se emiten AMBOS conjuntos de
    // tokens. El tema por defecto se elige según el plan:
    //   - `prefers-color-scheme: dark` → cambio automático según el SO.
    //   - `.dark` → toggle manual (clase) para el switch de la UI.
    // Si el plan pide `dark`, el tema oscuro es el por defecto.
    let (light_default, dark_default) = if plan.app.theme == "dark" {
        ("prefers-color-scheme: dark", "color-scheme: dark;")
    } else {
        ("(prefers-color-scheme: dark)", "")
    };
    format!(
        r#"@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {{
  :root {{
    color-scheme: light;
    --background: 0 0% 100%;
    --foreground: 222 47% 11%;
    --primary: 221 83% 53%;
    --primary-foreground: 210 40% 98%;
    --border: 214 32% 91%;
    --radius: 0.5rem;
  }}

  /* Dark mode automático vía media query + toggle manual con .dark */
  @media {light_default} {{
    :root {{
      color-scheme: dark;
      --background: 224 71% 4%;
      --foreground: 213 31% 91%;
      --primary: 210 40% 98%;
    }}
  }}
  .dark {{
    color-scheme: {dark_default};
    --background: 224 71% 4%;
    --foreground: 213 31% 91%;
    --primary: 210 40% 98%;
    --border: 216 34% 17%;
  }}

  * {{
    @apply border-border;
  }}
  body {{
    @apply bg-background text-foreground;
  }}
}}
"#
    )
}

fn construir_vite_config() -> String {
    r#"import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(__dirname, './src') },
  },
});
"#
    .to_string()
}

fn construir_package_json(plan: &PlanComponentes) -> serde_json::Map<String, serde_json::Value> {
    let mut deps = serde_json::Map::new();
    let mut dev_deps = serde_json::Map::new();

    // Runtime básico.
    deps.insert("react".into(), json_v("18.3.1"));
    deps.insert("react-dom".into(), json_v("18.3.1"));

    // Dependencias del plan.
    for d in &plan.dependencies.runtime {
        if d != "react" && d != "react-dom" {
            deps.insert(d.clone(), json_v("latest"));
        }
    }
    for d in &plan.dependencies.ui {
        deps.insert(d.clone(), json_v("latest"));
    }
    for d in &plan.dependencies.utils {
        deps.insert(d.clone(), json_v("latest"));
    }
    for d in &plan.dependencies.styling {
        dev_deps.insert(d.clone(), json_v("latest"));
    }

    // Dev deps fijas.
    dev_deps.insert("typescript".into(), json_v("^5.6.3"));
    dev_deps.insert("vite".into(), json_v("^5.4.10"));
    dev_deps.insert("@vitejs/plugin-react".into(), json_v("^4.3.3"));
    dev_deps.insert("tailwindcss".into(), json_v("^3.4.14"));
    dev_deps.insert("postcss".into(), json_v("^8.4.47"));
    dev_deps.insert("autoprefixer".into(), json_v("^10.4.20"));

    // Base de shadcn/ui: dependencias que todas las plantillas de componentes
    // asumen como presentes (slot, cva, lucide-react). Sin declararlas,
    // gate_render marca los imports como `import_tercero_no_declarado`.
    deps.insert("class-variance-authority".into(), json_v("0.7.0"));
    deps.insert("@radix-ui/react-slot".into(), json_v("1.1.0"));
    deps.insert("lucide-react".into(), json_v("0.400.0"));
    deps.insert("clsx".into(), json_v("2.1.1"));
    deps.insert("tailwind-merge".into(), json_v("2.5.2"));

    // Dependencias @radix-ui/* que referencian los componentes shadcn usados.
    for radix in radix_deps_de(&plan.component_tree) {
        deps.insert(radix, json_v("latest"));
    }

    let mut pkg = serde_json::Map::new();
    pkg.insert(
        "name".into(),
        serde_json::Value::String(plan.app.name.clone()),
    );
    pkg.insert("version".into(), json_v("0.1.0"));
    pkg.insert("private".into(), serde_json::Value::Bool(true));
    pkg.insert("dependencies".into(), serde_json::Value::Object(deps));
    pkg.insert(
        "devDependencies".into(),
        serde_json::Value::Object(dev_deps),
    );
    pkg.insert(
        "scripts".into(),
        serde_json::json!({
            "dev": "vite",
            "build": "tsc && vite build",
            "preview": "vite preview"
        }),
    );
    pkg
}

fn json_v(v: &str) -> serde_json::Value {
    serde_json::Value::String(v.to_string())
}

/// Helper `cn` estándar de shadcn/ui (clsx + tailwind-merge). Emitido en
/// `src/lib/utils.ts` para que todos los imports `@/lib/utils` resuelvan.
const LIB_UTILS_TS: &str = r#"import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
"#;

// ─── Plantillas de componentes shadcn/ui ───────────────────────────────────

const BUTTON_TSX: &str = r#"import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const buttonVariants = cva(
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline: 'border border-input bg-background hover:bg-accent',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: { default: 'h-10 px-4 py-2', sm: 'h-9 px-3', lg: 'h-11 px-8' },
    },
    defaultVariants: { variant: 'default', size: 'default' },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button';
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = 'Button';

export { Button, buttonVariants };
"#;

const CARD_TSX: &str = r#"import * as React from 'react';
import { cn } from '@/lib/utils';

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('rounded-xl border bg-card text-card-foreground shadow', className)} {...props} />
  ),
);
Card.displayName = 'Card';

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('flex flex-col space-y-1.5 p-6', className)} {...props} />
  ),
);
CardHeader.displayName = 'CardHeader';

const CardTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn('font-semibold leading-none tracking-tight', className)} {...props} />
  ),
);
CardTitle.displayName = 'CardTitle';

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('p-6 pt-0', className)} {...props} />
  ),
);
CardContent.displayName = 'CardContent';

export { Card, CardContent, CardHeader, CardTitle };
"#;

const PROGRESS_TSX: &str = r#"import * as React from 'react';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import { cn } from '@/lib/utils';

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn('relative h-4 w-full overflow-hidden rounded-full bg-secondary', className)}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="h-full w-full flex-1 bg-primary transition-all"
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
"#;

const BADGE_TSX: &str = r#"import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const badgeVariants = cva(
  'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors',
  {
    variants: {
      variant: {
        default: 'border-transparent bg-primary text-primary-foreground',
        secondary: 'border-transparent bg-secondary text-secondary-foreground',
        destructive: 'border-transparent bg-destructive text-destructive-foreground',
        outline: 'text-foreground',
      },
    },
    defaultVariants: { variant: 'default' },
  },
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return <div className={cn(badgeVariants({ variant }), className)} {...props} />;
}

export { Badge, badgeVariants };
"#;

const SEPARATOR_TSX: &str = r#"import * as React from 'react';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import { cn } from '@/lib/utils';

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
  <SeparatorPrimitive.Root
    ref={ref}
    decorative={decorative}
    orientation={orientation}
    className={cn('shrink-0 bg-border', orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]', className)}
    {...props}
  />
));
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };
"#;

const INPUT_TSX: &str = r#"import * as React from 'react';
import { cn } from '@/lib/utils';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => (
    <input
      type={type}
      className={cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      ref={ref}
      {...props}
    />
  ),
);
Input.displayName = 'Input';

export { Input };
"#;

const LABEL_TSX: &str = r#"import * as React from 'react';
import * as LabelPrimitive from '@radix-ui/react-label';
import { cn } from '@/lib/utils';

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', className)}
    {...props}
  />
));
Label.displayName = LabelPrimitive.Root.displayName;

export { Label };
"#;

const SELECT_TSX: &str = r#"import * as React from 'react';
import * as SelectPrimitive from '@radix-ui/react-select';
import { Check, ChevronDown } from 'lucide-react';
import { cn } from '@/lib/utils';

const Select = SelectPrimitive.Root;
const SelectValue = SelectPrimitive.Value;

const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn('flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none disabled:cursor-not-allowed disabled:opacity-50', className)}
    {...props}
  >
    {children}
    <SelectPrimitive.Icon asChild>
      <ChevronDown className="h-4 w-4 opacity-50" />
    </SelectPrimitive.Icon>
  </SelectPrimitive.Trigger>
));
SelectTrigger.displayName = SelectPrimitive.Trigger.displayName;

const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Portal>
    <SelectPrimitive.Content
      ref={ref}
      className={cn('relative z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md', className)}
      {...props}
    >
      <SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport>
    </SelectPrimitive.Content>
  </SelectPrimitive.Portal>
));
SelectContent.displayName = SelectPrimitive.Content.displayName;

const SelectItem = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Item
    ref={ref}
    className={cn('relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent focus:text-accent-foreground', className)}
    {...props}
  >
    <span className="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
      <SelectPrimitive.ItemIndicator>
        <Check className="h-4 w-4" />
      </SelectPrimitive.ItemIndicator>
    </span>
    <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
  </SelectPrimitive.Item>
));
SelectItem.displayName = SelectPrimitive.Item.displayName;

export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue };
"#;

const DIALOG_TSX: &str = r#"import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';

const Dialog = DialogPrimitive.Root;
const DialogTrigger = DialogPrimitive.Trigger;
const DialogClose = DialogPrimitive.Close;

const DialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <DialogPrimitive.Portal>
    <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/80" />
    <DialogPrimitive.Content
      ref={ref}
      className={cn('fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg', className)}
      {...props}
    >
      {children}
      <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 transition-opacity hover:opacity-100">
        <X className="h-4 w-4" />
      </DialogPrimitive.Close>
    </DialogPrimitive.Content>
  </DialogPrimitive.Portal>
));
DialogContent.displayName = DialogPrimitive.Content.displayName;

const DialogHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('flex flex-col space-y-1.5 text-center sm:text-left', className)} {...props} />
);
const DialogTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Title ref={ref} className={cn('text-lg font-semibold leading-none tracking-tight', className)} {...props} />
));
DialogTitle.displayName = DialogPrimitive.Title.displayName;
const DialogDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />
));
DialogDescription.displayName = DialogPrimitive.Description.displayName;

export { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger };
"#;

const TABLE_TSX: &str = r#"import * as React from 'react';
import { cn } from '@/lib/utils';

const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
  ({ className, ...props }, ref) => (
    <div className="relative w-full overflow-auto">
      <table ref={ref} className={cn('w-full caption-bottom text-sm', className)} {...props} />
    </div>
  ),
);
Table.displayName = 'Table';

const TableHeader = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <thead ref={ref} className={cn('[&_tr]:border-b', className)} {...props} />
  ),
);
TableHeader.displayName = 'TableHeader';

const TableBody = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <tbody ref={ref} className={cn('[&_tr:last-child]:border-0', className)} {...props} />
  ),
);
TableBody.displayName = 'TableBody';

const TableRow = React.forwardRef<HTMLTableRowElement, React.HTMLAttributes<HTMLTableRowElement>>(
  ({ className, ...props }, ref) => (
    <tr ref={ref} className={cn('border-b transition-colors hover:bg-muted/50', className)} {...props} />
  ),
);
TableRow.displayName = 'TableRow';

const TableHead = React.forwardRef<HTMLTableCellElement, React.ThHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <th ref={ref} className={cn('h-12 px-4 text-left align-middle font-medium text-muted-foreground', className)} {...props} />
  ),
);
TableHead.displayName = 'TableHead';

const TableCell = React.forwardRef<HTMLTableCellElement, React.TdHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <td ref={ref} className={cn('p-4 align-middle', className)} {...props} />
  ),
);
TableCell.displayName = 'TableCell';

export { Table, TableBody, TableCell, TableHead, TableHeader, TableRow };
"#;

const AVATAR_TSX: &str = r#"import * as React from 'react';
import * as AvatarPrimitive from '@radix-ui/react-avatar';
import { cn } from '@/lib/utils';

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Root ref={ref} className={cn('relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full', className)} {...props} />
));
Avatar.displayName = AvatarPrimitive.Root.displayName;

const AvatarImage = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Image>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Image ref={ref} className={cn('aspect-square h-full w-full', className)} {...props} />
));
AvatarImage.displayName = AvatarPrimitive.Image.displayName;

const AvatarFallback = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Fallback>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Fallback
    ref={ref}
    className={cn('flex h-full w-full items-center justify-center rounded-full bg-muted', className)}
    {...props}
  />
));
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName;

export { Avatar, AvatarFallback, AvatarImage };
"#;

const SWITCH_TSX: &str = r#"import * as React from 'react';
import * as SwitchPrimitives from '@radix-ui/react-switch';
import { cn } from '@/lib/utils';

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn('peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent bg-input transition-colors focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary', className)}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb className="pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5" />
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };
"#;

const CHECKBOX_TSX: &str = r#"import * as React from 'react';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import { Check } from 'lucide-react';
import { cn } from '@/lib/utils';

const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn('peer h-4 w-4 shrink-0 rounded-sm border border-primary focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground', className)}
    {...props}
  >
    <CheckboxPrimitive.Indicator className="flex items-center justify-center text-current">
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
));
Checkbox.displayName = CheckboxPrimitive.Root.displayName;

export { Checkbox };
"#;

const TOOLTIP_TSX: &str = r#"import * as React from 'react';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { cn } from '@/lib/utils';

const TooltipProvider = TooltipPrimitive.Provider;
const Tooltip = TooltipPrimitive.Root;
const TooltipTrigger = TooltipPrimitive.Trigger;

const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn('z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground', className)}
    {...props}
  />
));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;

export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger };
"#;

const TOAST_TSX: &str = r#"import * as React from 'react';
import * as ToastPrimitives from '@radix-ui/react-toast';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';

const ToastProvider = ToastPrimitives.Provider;
const ToastViewport = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Viewport>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Viewport>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Viewport
    ref={ref}
    className={cn('fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:right-0 sm:top-auto sm:flex-col md:max-w-[420px]', className)}
    {...props}
  />
));
ToastViewport.displayName = ToastPrimitives.Viewport.displayName;

const Toast = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Root>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Root
    ref={ref}
    className={cn('group pointer-events-auto relative flex w-full items-center justify-between space-x-4 overflow-hidden rounded-md border p-6 pr-8 shadow-lg', className)}
    {...props}
  />
));
Toast.displayName = ToastPrimitives.Root.displayName;

const ToastTitle = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Title>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Title>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Title ref={ref} className={cn('text-sm font-semibold', className)} {...props} />
));
ToastTitle.displayName = ToastPrimitives.Title.displayName;

const ToastDescription = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Description>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Description>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Description ref={ref} className={cn('text-sm opacity-90', className)} {...props} />
));
ToastDescription.displayName = ToastPrimitives.Description.displayName;

const ToastClose = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Close>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Close>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Close
    ref={ref}
    className={cn('absolute right-2 top-2 rounded-md p-1 text-foreground/50 opacity-0 transition-opacity hover:text-foreground group-hover:opacity-100', className)}
    toast-close=""
    {...props}
  >
    <X className="h-4 w-4" />
  </ToastPrimitives.Close>
));
ToastClose.displayName = ToastPrimitives.Close.displayName;

export { Toast, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport };
"#;

const ALERT_DIALOG_TSX: &str = r#"import * as React from 'react';
import * as AlertDialogPrimitive from '@radix-ui/react-alert-dialog';
import { cn } from '@/lib/utils';

const AlertDialog = AlertDialogPrimitive.Root;
const AlertDialogTrigger = AlertDialogPrimitive.Trigger;

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Portal>
    <AlertDialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/80" />
    <AlertDialogPrimitive.Content
      ref={ref}
      className={cn('fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg', className)}
      {...props}
    />
  </AlertDialogPrimitive.Portal>
));
AlertDialogContent.displayName = AlertDialogPrimitive.Content.displayName;

const AlertDialogHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('flex flex-col space-y-2 text-center sm:text-left', className)} {...props} />
);

const AlertDialogTitle = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Title ref={ref} className={cn('text-lg font-semibold', className)} {...props} />
));
AlertDialogTitle.displayName = AlertDialogPrimitive.Title.displayName;

const AlertDialogDescription = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Description ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />
));
AlertDialogDescription.displayName = AlertDialogPrimitive.Description.displayName;

const AlertDialogAction = AlertDialogPrimitive.Action;
const AlertDialogCancel = AlertDialogPrimitive.Cancel;

export {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription,
  AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger,
};
"#;

const TABS_TSX: &str = r#"import * as React from 'react';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import { cn } from '@/lib/utils';

const Tabs = TabsPrimitive.Root;

const TabsList = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.List>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.List>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.List
    ref={ref}
    className={cn('inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground', className)}
    {...props}
  />
));
TabsList.displayName = TabsPrimitive.List.displayName;

const TabsTrigger = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Trigger>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.Trigger
    ref={ref}
    className={cn('inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground', className)}
    {...props}
  />
));
TabsTrigger.displayName = TabsPrimitive.Trigger.displayName;

const TabsContent = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Content>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.Content
    ref={ref}
    className={cn('mt-2 ring-offset-background focus-visible:outline-none', className)}
    {...props}
  />
));
TabsContent.displayName = TabsPrimitive.Content.displayName;

export { Tabs, TabsContent, TabsList, TabsTrigger };
"#;

const SCROLL_AREA_TSX: &str = r#"import * as React from 'react';
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
import { cn } from '@/lib/utils';

const ScrollArea = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
>(({ className, children, ...props }, ref) => (
  <ScrollAreaPrimitive.Root ref={ref} className={cn('relative overflow-hidden', className)} {...props}>
    <ScrollAreaPrimitive.Viewport className="h-full w-full rounded-[inherit]">{children}</ScrollAreaPrimitive.Viewport>
    <ScrollBar />
    <ScrollAreaPrimitive.Corner />
  </ScrollAreaPrimitive.Root>
));
ScrollArea.displayName = ScrollAreaPrimitive.Root.displayName;

const ScrollBar = React.forwardRef<
  React.ElementRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>
>(({ className, orientation = 'vertical', ...props }, ref) => (
  <ScrollAreaPrimitive.ScrollAreaScrollbar
    ref={ref}
    orientation={orientation}
    className={cn('flex touch-none select-none transition-colors', orientation === 'vertical' && 'h-full w-2.5 border-l border-l-transparent p-[1px]', className)}
    {...props}
  >
    <ScrollAreaPrimitive.ScrollAreaThumb className="relative flex-1 rounded-full bg-border" />
  </ScrollAreaPrimitive.ScrollAreaScrollbar>
));
ScrollBar.displayName = ScrollAreaPrimitive.ScrollAreaScrollbar.displayName;

export { ScrollArea, ScrollBar };
"#;

const DROPDOWN_MENU_TSX: &str = r#"import * as React from 'react';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import { cn } from '@/lib/utils';

const DropdownMenu = DropdownMenuPrimitive.Root;
const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;

const DropdownMenuContent = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <DropdownMenuPrimitive.Portal>
    <DropdownMenuPrimitive.Content
      ref={ref}
      sideOffset={sideOffset}
      className={cn('z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md', className)}
      {...props}
    />
  </DropdownMenuPrimitive.Portal>
));
DropdownMenuContent.displayName = DropdownMenuPrimitive.Content.displayName;

const DropdownMenuItem = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Item>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Item
    ref={ref}
    className={cn('relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground', className)}
    {...props}
  />
));
DropdownMenuItem.displayName = DropdownMenuPrimitive.Item.displayName;

const DropdownMenuLabel = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Label>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Label>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Label ref={ref} className={cn('px-2 py-1.5 text-sm font-semibold', className)} {...props} />
));
DropdownMenuLabel.displayName = DropdownMenuPrimitive.Label.displayName;

const DropdownMenuSeparator = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Separator>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Separator>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Separator ref={ref} className={cn('-mx-1 my-1 h-px bg-muted', className)} {...props} />
));
DropdownMenuSeparator.displayName = DropdownMenuPrimitive.Separator.displayName;

export {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger,
};
"#;

const CALENDAR_TSX: &str = r#"import * as React from 'react';
import { DayPicker } from 'react-day-picker';
import { cn } from '@/lib/utils';

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({ className, ...props }: CalendarProps) {
  return (
    <DayPicker
      className={cn('p-3', className)}
      showOutsideDays
      {...props}
    />
  );
}
Calendar.displayName = 'Calendar';

export { Calendar };
"#;

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cerebro::v0::planner::Planificador;
    use crate::cerebro::v0::DependenciasPlan;

    fn plan_basico() -> PlanComponentes {
        PlanComponentes {
            schema: super::super::contracts::V0_SCHEMA_PLAN.into(),
            app: super::super::contracts::AppSpec {
                name: "mi-app".into(),
                description: "App de prueba".into(),
                framework: "react".into(),
                styling: "tailwind".into(),
                component_library: "shadcn/ui".into(),
                theme: "light".into(),
            },
            page_tree: vec![super::super::contracts::RoutePlan {
                path: "/".into(),
                component: "App".into(),
                layout: "default".into(),
            }],
            component_tree: NodoComponente {
                name: "App".into(),
                source: "local".into(),
                props: Default::default(),
                children: vec![NodoComponente {
                    name: "Button".into(),
                    source: "shadcn/ui".into(),
                    props: Default::default(),
                    children: vec![],
                }],
            },
            dependencies: DependenciasPlan {
                runtime: vec!["react".into(), "react-dom".into()],
                ui: vec!["lucide-react".into()],
                styling: vec!["tailwindcss".into()],
                utils: vec!["clsx".into()],
            },
            state_shape: super::super::contracts::StateShape {
                use_state: vec![],
                use_reducer: vec![],
                context: vec![],
            },
        }
    }

    #[test]
    fn test_generar_app_tsx_y_archivos() {
        let mut g = Generador::nuevo();
        let gen = g.generar_local(&plan_basico());
        assert_eq!(gen.entry_point, "src/App.tsx");
        assert_eq!(gen.schema, super::super::contracts::V0_SCHEMA_GENERATE);

        let paths: Vec<&str> = gen.files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"src/App.tsx"));
        assert!(paths.contains(&"tailwind.config.ts"));
        assert!(paths.contains(&"src/index.css"));
        assert!(paths.contains(&"vite.config.ts"));

        // button.tsx y card.tsx siempre generados.
        assert!(paths.contains(&"src/components/ui/button.tsx"));
        assert!(paths.contains(&"src/components/ui/card.tsx"));

        // El App.tsx importa el Button.
        let app = gen.files.iter().find(|f| f.path == "src/App.tsx").unwrap();
        assert!(app
            .content
            .contains("import { Button } from '@/components/ui/button'"));
    }

    #[test]
    fn test_generar_con_dashboard_incluye_componentes() {
        let plan = Planificador::nuevo()
            .planificar_local("dashboard de ventas")
            .plan;
        let mut g = Generador::nuevo();
        let gen = g.generar_local(&plan);
        let paths: Vec<&str> = gen.files.iter().map(|f| f.path.as_str()).collect();
        // Dashboard usa Progress y Card.
        assert!(paths.contains(&"src/components/ui/progress.tsx"));
    }

    #[test]
    fn test_package_json_contiene_deps() {
        let mut g = Generador::nuevo();
        let gen = g.generar_local(&plan_basico());
        let pkg = &gen.package_json;
        assert_eq!(pkg.get("name").unwrap(), "mi-app");
        let deps = pkg.get("dependencies").unwrap().as_object().unwrap();
        assert!(deps.contains_key("react"));
        assert!(deps.contains_key("react-dom"));
        let dev = pkg.get("devDependencies").unwrap().as_object().unwrap();
        assert!(dev.contains_key("typescript"));
        assert!(dev.contains_key("vite"));
    }

    #[test]
    fn test_plan_id_estable() {
        let mut g = Generador::nuevo();
        let p1 = plan_basico();
        let id1 = g.generar_local(&p1).plan_id;
        let p2 = plan_basico();
        let id2 = g.generar_local(&p2).plan_id;
        assert_eq!(id1, id2);
        assert!(id1.starts_with("plan-"));
    }

    #[test]
    fn test_pascal_case() {
        assert_eq!(pascal_case("dropdown-menu"), "DropdownMenu");
        assert_eq!(pascal_case("alert-dialog"), "AlertDialog");
        assert_eq!(pascal_case("button"), "Button");
    }

    #[test]
    fn test_generar_gemini_fallback_sin_api() {
        let plan = Planificador::nuevo().planificar_local("landing").plan;
        let mut g = Generador::nuevo();
        let rt = tokio::runtime::Runtime::new().unwrap();
        let gen = rt.block_on(g.generar_gemini(&plan, None)).unwrap();
        assert_eq!(gen.entry_point, "src/App.tsx");
    }

    #[test]
    fn test_tema_dark_en_css() {
        let mut plan = plan_basico();
        plan.app.theme = "dark".into();
        let mut g = Generador::nuevo();
        let gen = g.generar_local(&plan);
        let css = gen
            .files
            .iter()
            .find(|f| f.path == "src/index.css")
            .unwrap();
        assert!(css.content.contains(".dark"));
    }

    // FASE 5 — Dark/light mode automático: el CSS siempre emite ambos temas.
    #[test]
    fn test_dark_light_automatico_siempre_emite_ambos_temas() {
        let plan = plan_basico(); // theme por defecto (light)
        let mut g = Generador::nuevo();
        let gen = g.generar_local(&plan);
        let css = gen
            .files
            .iter()
            .find(|f| f.path == "src/index.css")
            .unwrap()
            .content
            .clone();

        // Tema claro (tokens por defecto).
        assert!(css.contains("--background: 0 0% 100%"));
        // Toggle manual.
        assert!(css.contains(".dark"));
        // Media query para cambio automático según preferencia del SO.
        assert!(css.contains("prefers-color-scheme"));
        // Tokens oscuros presentes.
        assert!(css.contains("--background: 224 71% 4%"));
    }
}
